### ISSUE TITLE
可不可以更新一个readme文件

### ISSUE THREAD

**Issue by DWendou** [dayekuaipao/surroundview3d#1]
教一下编译流程，谢谢啦

**Comment by DWendou** [comment]
怎么使用这个工程

**Comment by dayekuaipao** [comment]
I will do it in the future. In general, you need to install glad, glfw, OpenCV and OpenCV-contrib. After installation, you can use cmake and the cmakelists.txt is in the repo.

**Comment by DWendou** [comment]
> I will do it in the future. In general, you need to install glad, glfw, OpenCV and OpenCV-contrib. After installation, you can use cmake and the cmakelists.txt is in the repo.

thank you，I've compiled successfully，but i don't understand the result of rendering

**Comment by dayekuaipao** [comment]
> 

Well, you need do some preparation, such as calibrate the intrinsic and extrinsic of four cameras and choose the right format of your camera.

**Comment by dayekuaipao** [comment]
The result of the 3D surround view is like a bowl and the picture of the camera will be rendered on the surface of it.

**Comment by DWendou** [comment]
看了你最新更新的代码，你创建的碗状模型，把前后左右四个摄像头的图像贴上去，但是我出来的结果就很奇怪，我的相机内参、外参都是按照代码生成的，我没有摄像头信息，我直接拿四张图像，传入进去的。纹理没有贴上去.......
![image](https://user-images.githubusercontent.com/49715088/195783990-a63fa638-5c5b-4f60-bc94-951bb757087d.png)

**Comment by dayekuaipao** [comment]
How did you get the extrinsic? You need to calibrate it by yourself.

**Comment by dayekuaipao** [comment]
In the meanwhile, you need to choose the right format of your camera.

**Comment by dayekuaipao** [comment]
I may update a readme or a blog this weekend.

**Comment by DWendou** [comment]
非常谢谢你的耐心回复，我是您的main.cpp中的代码生成的相关参数，相机的内参、外参、畸变系数、还有xi。你的代码好像是读取四个实时摄像头的，但是我目前没有摄像头，只是图片。可能是我的参数设置有问题吧。不过还是非常感谢您的知道，也非常期待您的更新。祝您生活愉快。

**Comment by dayekuaipao** [comment]
Well, I`ve found a great blog about this topic, you can refrence https://zhuanlan.zhihu.com/p/534553717.

**Comment by DWendou** [comment]
I've been expecting you to update a README，thank you

**Comment by DWendou** [comment]
最近重新看你的这个工程，在main.cpp中的106行到114行的这段注释掉的这段计算外参的代码，变量parameter在哪里定义的？
// Mat worldPoints;
// string worldPointsString = "WorldPoints"+to_string(c);
// parameter[worldPointsString]>>worldPoints;

// Mat imagePoints;
// string imagePointsString = "ImagePoints"+to_string(c);
// parameter[imagePointsString]>>imagePoints;

//cameraModel->computeRT(imagePoints,worldPoints);

**Comment by dayekuaipao** [comment]
I have updated this project.
